petram/mfem_viewer.py, petram/pi/dlg_submit_job.py, petram/remote/client_script.py, setup.py
This pull add
* E-mail notification setting for cluster jobs
* log/keywords setting in job submission panel
* minor fix for wx4.1.
=> Log notification dev

petram/pi/dlg_submit_job.py, petram/remote/client_script.py
FIxed a few issues. Seems to work between jiji and MIT
=> This one works on MIT

petram/engine.py, petram/mfem_viewer.py, petram/pi/dlg_submit_job.py, petram/solver/parametric.py
This pull clean up GUI behaviour during a job submission
* dialog title is fixed
* error dialog pops up when no keywords are selected
* record the cluster connection correctly when a user has multiple connections.
=> Job submission title fix

petram/helper/variables.py, petram/mfem_viewer.py, petram/model.py, petram/phys/phys_model.py, petram/phys/weakform.py, petram/phys/wf/wf_constraints.py, petram/phys/wf/wf_model.py, petram/pi/dlg_plot_sol.py, petram/sol/solsets.py, setup.py
This pull
* added utility routines to add variables after solve
* fixed interface issue when using multiple local solve solution directory
* weakform interface update to show proper list of integrators
* 1D edge plot supports wave field.
=> Branch4merge

petram/engine.py, petram/helper/variables.py, petram/mfem_viewer.py, petram/namespace_mixin.py, petram/pi/dlg_plot_sol.py, petram/pi/dlg_submit_job.py, petram/sol/evaluator_mp.py, petram/sol/ncface_evaluator.py, petram/sol/pointcloud_evaluator.py, petram/solver/solver_model.py, setup.py
This pull includes the following
* evaluators handle the namespace variables which has a dependence properly
* pointcloud evaluate PyFunction variables 
* namespace rebuild shows error/success dialog
* evaluator returns proper error message from child processes
* slice Grid plot shows the slice on the correct place in 3D
* minor bug fix
=> PointCloudFix and others

petram/phys/vtable.py
This pull fix array element interface
=> Fix vtable array

petram/helper/variables.py, petram/namespace_mixin.py, petram/phys/vtable.py, petram/pi/dlg_plot_sol.py, setup.py
This pull
* remove \n when loading the name space script from file. This allows the line
concatenation done by backslash not ().
* accept multidimensional array in point-cloud plot
* minor fix (window title update) when pointcloud export is done
=> remove extra new-line from namespace compile

petram/pi/dlg_plot_sol.py, petram/solver/mumps_model.py, setup.py
This extend mumps_solver interface to add
* save factor option
* additional ordering options
=> Mumps save scotch

petram/helper/variables.py, petram/pi/dlg_plot_sol.py, petram/remote/client_script.py, setup.py
This pull modify plot panel so that it allows for 
* reading data from an arbitrary local directory.
* recording the remote directories in pull-down menu
It also
* avoid hang-up when ssh connection was not properly setup
* error message shows more useful information
=> Plot sol dev

petram/engine.py, petram/mesh/mesh_model.py
This is to let the sub-classes the possibility to have different
implementations for the serial and parallel meshes
=> Adds run_serial to the Mesh base class

petram/mesh/mesh_inspect.py, petram/mesh/mesh_model.py, petram/mesh/refined_mfem_geom.py, setup.py
This pull add topology checker based on the logic used in 
https://github.com/mfem/mfem/blob/master/mesh/mesh.cpp#L2611
mesh_inspect.find_invalid_topology implement the same logic.
Reload mesh and Check topology buttons are added in mesh_model GUI panel
=> Mesh topology checker

petram/helper/preconditioners.py, petram/helper/variables.py, petram/mesh/mesh_inspect.py, petram/mesh/mesh_model.py, petram/mfem_viewer.py, petram/pi/dlg_edit_model.py, petram/pi/dlg_plot_sol.py, petram/pi/dlg_submit_job.py, petram/remote/client_script.py, petram/solver/iterative_model.py, petram/solver/mumps_model.py, setup.py
This pull increase
* Interface to a nest Klyrov
* add an option to use single precision in MUMPS
* minor improvement of GUI response
=> Preconditioner improvement

petram/mesh/geo_plot.py, petram/mesh/mesh_model.py, petram/mesh/plot_mesh.py, petram/mesh/read_mfemmesh.py, petram/mesh/read_mfemmesh2.py, petram/mfem_viewer.py, petram/namespace_mixin.py, petram/phys/phys_model.py, petram/pi/dlg_edit_model.py, petram/pi/dlg_plot_sol.py, petram/sol/bdr_nodal_evaluator.py, petram/sol/listsoldir.py, petram/sol/ncface_evaluator.py, setup.py
This pull add 
* proper handling of mixed element high-order mesh for geometry visualization
* adjustment to add custom intorder
=> High order mixed mesh and solution vis. + custom int-order 

petram/engine.py, petram/mesh/partial_mesh.py, setup.py
This pull fix mesh partitioning from running into a infinite loop with MFEM4.2
=> Small mesh partitioning fix

petram/engine.py, petram/helper/convolv1d.py, petram/helper/convolve1d.py, petram/helper/dof_map.py, petram/helper/expression.py, petram/helper/mpi_recipes.py, petram/helper/operators.py, petram/pi/dlg_plot_sol.py, petram/remote/client_script.py, petram/sol/evaluator_cs.py, petram/sol/evaluator_single.py, petram/sol/evaluators.py, petram/solver/mumps_model.py, petram/solver/strumpack_model.py, setup.py
This pull request includes
* Strumpack solver interface update for ST 5.0.0
* convolution operator for 1D
* supports multiplexed SSH connection
=> Strumpack update

petram/mfem_viewer.py
minor fix to address wxpython API changes
=> fixed one error

petram/engine.py, petram/helper/convolve.py, petram/helper/convolve1d.py, petram/helper/expression.py, petram/helper/operators.py, petram/helper/variables.py, petram/mesh/mesh_utils.py, petram/mfem_model.py, petram/mfem_viewer.py, petram/model.py, petram/namespace_mixin.py, petram/phys/aux_operator.py, petram/phys/phys_model.py, petram/phys/weakform.py, petram/phys/wf/wf_model.py, petram/pi/dlg_edit_model.py, petram/pi/dlg_plot_sol.py, petram/postprocess/discrt_v_integration.py, petram/postprocess/pp_model.py, petram/sol/bdr_nodal_evaluator.py, petram/sol/evaluator_cs.py, petram/sol/evaluator_mp.py, petram/sol/evaluator_single.py, petram/sol/evaluators.py, petram/sol/integral_evaluator.py, setup.py
This pull add an initial implementation of 
* integral evaluator
* convolution integral in 1D/2D 
These features needs to be tested more...
=> Integral evaluator

petram/engine.py, petram/helper/dof_map.py, petram/mesh/make_simplemesh.py, setup.py
This pull
* fix handling periodic BC (or interpolation constraints) when there are multiple FES in the model
* address a minor deprecation error
* fixed DoF mapper when all vector elements are the same (this error occurredwhen mapping edge to of vector FES)
* DoF mapper support mapping L2 on 1D mesh.
=> Fix periodic

petram/helper/dof_map.py
Minor fix to RT to RT-Trace DoF mapping matrix
=> put weight in RF mapping

petram/engine.py, petram/helper/block_matrix.py, petram/helper/convolve.py, petram/helper/dof_map.py, petram/helper/operators.py, petram/phys/coefficient.py, petram/phys/weakform.py, petram/phys/wf/wf_constraints.py, setup.py
This is on-going work but has passed test. This includes
* fix of DoF_mapper for ND surface, RT surface
* fix diagonal block handling in serial mode
=> convolution_profiling.

petram/engine.py, petram/helper/dof_map.py, petram/helper/variables.py, petram/phys/phys_model.py, petram/phys/weakform.py, petram/phys/wf/wf_model.py, petram/pi/dlg_edit_model.py, setup.py
This pull fixed to create 2D Vector RT elements (not Trace) on surface on volume.
=> Rtnd low dim

petram/engine.py, petram/init_model.py, petram/phys/coefficient.py, petram/phys/distance/distance_model.py, petram/phys/distance/wall.py, petram/pi/dlg_plot_sol.py, petram/solver/distance_solver.py, petram/solver/mumps_model.py, petram/solver/solver_model.py, setup.py
This PR includes
1) Distance calculation interface.
2) a minor change in MUMPS block preconditioner to use multiple pre-computed factors.
=> Interface to compute approximate distance from wall

petram/engine.py, petram/helper/convolve.py, petram/helper/matrix_file.py, petram/helper/operators.py, petram/mesh/geo_plot.py, petram/mfem_model.py, petram/phys/wf/wf_model.py, petram/phys/wf/wf_natural.py, petram/pi/dlg_plot_sol.py, petram/remote/client_script.py, petram/solver/mumps_model.py, petram/solver/solver_model.py, petram/solver/std_solver_model.py, setup.py
* added mes partitioning by_attribute
* added space dependent coefficient support to convolution integral
* minor change to cluster job submission tools to be more reusable.
* changed matrix file format and default precision to 8 digitits
* fixed geo_plot was not using integer for array_idx when a mesh is high order. 
* added wf_natural. this is a BC not specifying anything. Can be used for internal_bdr to change what is selected by "remaining".
* added "skip_solve" and "load_sol" option. These are switches to load solution which was linear-solved outside Petra-M.
* version number 1.8.6 (from 1.8.3)
=> Accumurated updates from mg_support

petram/engine.py, petram/helper/operators.py, petram/namespace_mixin.py, petram/solver/ml_solver_model.py, petram/solver/parametric.py, petram/solver/std_solver_model.py, setup.py
added pp for parametric scan
* fixed mask handling to check if elimination matrix must be re-created.
* identity operator now uses coefficient
* minor edit
=> Add pp for parametirc

petram/engine.py, petram/helper/direct_wrapper_call.py, petram/helper/mpi_helpers.py, petram/helper/mpi_recipes.py, petram/model.py, petram/namespace_mixin.py, petram/phys/phys_model.py, petram/phys/weakform.py, petram/pi/dlg_plot_sol.py, petram/sol/bdr_nodal_evaluator.py, petram/sol/edge_nodal_evaluator.py, petram/sol/ncedge_evaluator.py, petram/solver/mumps_model.py, petram/solver/parametric.py, petram/solver/solver_controls.py, petram/solver/solver_model.py, petram/solver/std_solver_model.py, setup.py
merging this to mg_support to test.
1) added forloop under parametric scan
2) fixed edge plot
3) added innterforloop
4) trying to fix namespace handling in complicated scenarios
=> Forloop inside parametric

petram/sol/bdr_nodal_evaluator.py
=> minor fix + autopep8

petram/engine.py, petram/phys/aux_variable.py, petram/postprocess/discrt_v_integration.py, petram/sol/probe.py, petram/solver/parametric.py, petram/solver/solver_model.py
Merges this to nl_solver_dev for now to simply the working branch
=> Parametric optimization dev

petram/engine.py, petram/mesh/mesh_model.py
=> Job submission adjustment

petram/pi/dlg_plot_sol.py, petram/sol/pointcloud_evaluator.py
This PR added
* multislce plane plot
* fixed domain selection in slice plot
* added a couple of help tip in dlg_sol_plot
=> Multislice plot

petram/debug.py, petram/engine.py, petram/helper/variables.py, petram/phys/numba_coefficient.py, petram/pi/dlg_plot_sol.py, petram/pi/shell_commands.py, petram/sol/evaluator_cs.py, petram/sol/evaluator_mp.py, petram/sol/evaluators.py, petram/solver/mumps_model.py, petram/solver/parametric.py, petram/solver/std_solver_model.py, petram/solver/strumpack_model.py, setup.py
This PR contains changes to
* avoid multiple compile of same numba function
* fix coefficient dependency on other function coefficient
* add remote plot debug option using debug_evaluator_mp flag
* keep sol distributed when MUMPS or STRUMPACK is used as a main linear solver
* related fix in parametric solver
=> Distributed rhs sol directsolver

petram/helper/numba_interp.py, petram/mesh/partial_mesh.py, setup.py
This PR allows
* interpolation using numba when x is not uniformly spaced
=> Fix numba interp

petram/mesh/mesh_model.py
This PR add an option to renumber the mesh file attribute / boundary attribute
when a new mesh file is loaded.
=> added an option to renumber the attribute/boundary attribute

petram/namespace_mixin.py, petram/pi/widget_parameters.py, setup.py
This PR changes the logic to generate child namespace
* Parent are not compiled separately. Instead, the names in parent namespaces are copied.
* * This allows to have the same class, global parameters shared (inherited) from parent
=> Namespace debug

petram/helper/variables.py, petram/model.py, petram/sol/bdr_nodal_evaluator.py, petram/sol/ncedge_evaluator.py, petram/sol/ncface_evaluator.py, petram/sol/pointcloud_evaluator.py
Fixed 
* grad/curl/div dependency used in PyFunction
* xxx_evauators are cleaned up  to use prep_names consistently and not to call dependency's Variables evaluation 
routine directly.
=> Fix grad dependency

petram/mfem_viewer.py, petram/phys/phys_const.py, petram/pi/dlg_export_opts.py, petram/pi/dlg_plot_sol.py, petram/pi/dlg_submit_job.py, petram/remote/client_script.py
This PR supports
* perform domain integration  for all parametric scan
* submit an SLURM array job
=> Update ingegration using subdirectories

petram/engine.py, petram/pi/dlg_edit_model.py, petram/solver/solver_model.py, petram/solver/superposition.py, setup.py
This PR add
* workflow to superposition solutions
* update rf_port_scanner to hold Smat data, so  that Smat can be used in the later SolveStep
=> Superposition dev
